export const FOODITEM_LIST_REQUEST = "FOODITEM_LIST_REQUEST";
export const FOODITEM_LIST_SUCCESS = "FOODITEM_LIST_SUCCESS";
export const FOODITEM_LIST_FAIL = "FOODITEM_LIST_FAIL";

export const FOODITEM_DETAILS_REQUEST = "FOODITEM_DETAILS_REQUEST";
export const FOODITEM_DETAILS_SUCCESS = "FOODITEM_DETAILS_SUCCESS";
export const FOODITEM_DETAILS_FAIL = "FOODITEM_DETAILS_FAIL";

export const FOODITEM_DELETE_REQUEST = "FOODITEM_DELETE_REQUEST";
export const FOODITEM_DELETE_SUCCESS = "FOODITEM_DELETE_SUCCESS";
export const FOODITEM_DELETE_FAIL = "FOODITEM_DELETE_FAIL";

export const FOODITEM_CREATE_REQUEST = "FOODITEM_CREATE_REQUEST";
export const FOODITEM_CREATE_SUCCESS = "FOODITEM_CREATE_SUCCESS";
export const FOODITEM_CREATE_FAIL = "FOODITEM_CREATE_FAIL";
export const FOODITEM_CREATE_RESET = "FOODITEM_CREATE_RESET";

export const FOODITEM_UPDATE_REQUEST = "FOODITEM_UPDATE_REQUEST";
export const FOODITEM_UPDATE_SUCCESS = "FOODITEM_UPDATE_SUCCESS";
export const FOODITEM_UPDATE_FAIL = "FOODITEM_UPDATE_FAIL";
export const FOODITEM_UPDATE_RESET = "FOODITEM_UPDATE_RESET";

export const FOODITEM_CREATE_REVIEW_REQUEST = "FOODITEM_CREATE_REVIEW_REQUEST";
export const FOODITEM_CREATE_REVIEW_SUCCESS = "FOODITEM_CREATE_REVIEW_SUCCESS";
export const FOODITEM_CREATE_REVIEW_FAIL = "FOODITEM_CREATE_REVIEW_FAIL";
export const FOODITEM_CREATE_REVIEW_RESET = "FOODITEM_CREATE_REVIEW_RESET";

export const FOODITEM_TOP_REQUEST = "FOODITEM_TOP_REQUEST";
export const FOODITEM_TOP_SUCCESS = "FOODITEM_TOP_SUCCESS";
export const FOODITEM_TOP_FAIL = "FOODITEM_TOP_FAIL";
