export const FOODITEM_LIST_REQUEST = "FOODITEM_LIST_REQUEST";
export const FOODITEM_LIST_SUCCESS = "FOODITEM_LIST_SUCCESS";
export const FOODITEM_LIST_FAIL = "FOODITEM_LIST_FAIL";

export const FOODITEM_DETAILS_REQUEST = "FOODITEM_DETAILS_REQUEST";
export const FOODITEM_DETAILS_SUCCESS = "FOODITEM_DETAILS_SUCCESS";
export const FOODITEM_DETAILS_FAIL = "FOODITEM_DETAILS_FAIL";

export const FOODITEM_DELETE_REQUEST = "FOODITEM_DELETE_REQUEST";
export const FOODITEM_DELETE_SUCCESS = "FOODITEM_DELETE_SUCCESS";
export const FOODITEM_DELETE_FAIL = "FOODITEM_DELETE_FAIL";

export const FOODITEM_CREATE_REQUEST = "FOODITEM_CREATE_REQUEST";
export const FOODITEM_CREATE_SUCCESS = "FOODITEM_CREATE_SUCCESS";
export const FOODITEM_CREATE_FAIL = "FOODITEM_CREATE_FAIL";
export const FOODITEM_CREATE_RESET = "FOODITEM_CREATE_RESET";

export const FOODITEM_UPDATE_REQUEST = "FOODITEM_UPDATE_REQUEST";
export const FOODITEM_UPDATE_SUCCESS = "FOODITEM_UPDATE_SUCCESS";
export const FOODITEM_UPDATE_FAIL = "FOODITEM_UPDATE_FAIL";
export const FOODITEM_UPDATE_RESET = "FOODITEM_UPDATE_RESET";

export const FOODITEM_CREATE_REVIEW_REQUEST = "FOODITEM_CREATE_REVIEW_REQUEST";
export const FOODITEM_CREATE_REVIEW_SUCCESS = "FOODITEM_CREATE_REVIEW_SUCCESS";
export const FOODITEM_CREATE_REVIEW_FAIL = "FOODITEM_CREATE_REVIEW_FAIL";
export const FOODITEM_CREATE_REVIEW_RESET = "FOODITEM_CREATE_REVIEW_RESET";

export const FOODITEM_TOP_REQUEST = "FOODITEM_TOP_REQUEST";
export const FOODITEM_TOP_SUCCESS = "FOODITEM_TOP_SUCCESS";
export const FOODITEM_TOP_FAIL = "FOODITEM_TOP_FAIL";



export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

